### ISSUE TITLE
Add a function that enables importing fees

### ISSUE THREAD

**Issue by c0nsol3** [Solar-network/python-crypto#18]
Currently all fees are hardcoded. It would be useful to have a `load_fees` function that can be used alongside `python-client` library to load fees from the network.

```py
import client
import crypto

fees = client.get_fees()
crypto.fees.load_fees(fees)
```
Above is just a pseudo-code.

**Comment by sleepdefic1t** [comment]
Closing this out.

Core is in flux atm, but a more fitting solution would be to copy its current behaviour by implementing milestone data as part of the configuration manager since it already contains both static _and_ dynamic fee info.

If for whatever reason some non-standard fee were needed, `set_fee` still exists.

This topic can be revisited after Core 5.0 is released.
